### ISSUE TITLE
[query] How can I remove the "close" button from the activity bar?

### ISSUE THREAD

**Issue by kwill** [deadalnix/pixel-saver#137]
When I maximise a window, I don't want the minimize, maximise or close button to appear in the activity bar. I have disabled the Maximize and Minimize buttons in the Tweak Tool, and they no longer appear.

How can I disable the Close (X) button so that it doesn't appear in the activity bar either? Ideally an unmaximized window will still show the Close button as usual.

**Comment by br4nnigan** [comment]
Funny, because I don't have buttons and I want them.

**Comment by deadalnix** [comment]
It follow gnome's config.

**Comment by kwill** [comment]
Answered in full here: https://askubuntu.com/questions/948313

> If you want to get rid of all the buttons from all windows, you may run the following command in Terminal:
>
> gsettings set org.gnome.desktop.wm.preferences button-layout :

Presumably other `button-layout` options are possible.

The answer also gives suggestions on how to modify your local copy of Pixel Saver so that buttons appear in regular windows but don't appear in maximised windows. But this will get changed every time Pixel Saver is updated.
