### ISSUE TITLE
Window control buttons on the left?

### ISSUE THREAD

**Issue by VaclavC** [deadalnix/pixel-saver#150]
Hello, this extension is great, especially for former (well, not sure yet ;-) Unity user.

But is there any option how to move window control buttons (close etc) to left side? I am able to do it for all non maximized windows with Gnome tweak tool, but with Pixel Saver they appear on the right between language input selector and rest of toolbar icons when maximized.

**Comment by VaclavC** [comment]
Nevermind, today they are on the left even with maximized window. Perhaps it needed simply relogin.

**Comment by deadalnix** [comment]
It gets the config from gconf at startup.
