### ISSUE TITLE
No title bar for Non-Maximised windows

### ISSUE THREAD

**Issue by JasoonS** [deadalnix/pixel-saver#154]
I would like to know if it is possible to add this feature (no title bar) for non-maximised windows?

This is a problem when using an extension like [ShellTile](https://extensions.gnome.org/extension/657/shelltile/), as seen in the image bellow.
![image](https://user-images.githubusercontent.com/6032276/36592922-5de1c904-18a0-11e8-9539-ad0c54ed356b.png)

The plugin works perfectly if the window is maximised.

**Comment by GuilloOme** [comment]
@JasoonS, you should give a try to Undecorate extension, this is what it does.

https://extensions.gnome.org/extension/1208/undecorate/

**Comment by JasoonS** [comment]
@GuilloOme Thank you very much! That works perfectly. A tiny bit annoying that you need to manually 'undecorate' each window, but I'm happy.
