### ISSUE TITLE
Two close icons with Libre Office

### ISSUE THREAD

**Issue by orschiro** [deadalnix/pixel-saver#157]
Hey @deadalnix,

Thanks for your great extension!

Just wanted to let you know that with LO, the extension produces two close icons on Fedora 27.

Can you confirm?

![screenshot from 2018-03-06 14-50-32](https://user-images.githubusercontent.com/170947/37035767-db4ac28c-214d-11e8-8a9d-da1f2481d484.png)

**Comment by keunes** [comment]
I have the same on Ubuntu (18.04 with Yaru theme):
/files/Pictures/Screenshot from 2018-11-04 14-34-02.png

Please note that this is normal behaviour: in close in the top bar closes the window (or whole LibreOffice), the one below (right side of the menu bar) closes the document. If you disable this extension, you'll still have two 'close' icons.

Guess this issue can be closed.
