### ISSUE TITLE
Disable?

### ISSUE THREAD

**Issue by tony-nowatzki** [deadalnix/pixel-saver#175]
The extension remains on, after disabling or even after deleting .local/share/gnome-shell/extensions

How do I disable?

**Comment by franglais125** [comment]
I had the same problem way back. In my testing, the extension never got disabled at all due to a bug. If you can provide a log, we can pinpoint it. IIRC, I fixed it here https://github.com/franglais125/no-title-bar/commit/b2c498048f84a88d2a1b75d3996f4f8cd8028d8a (can't be 100% sure).

Otherwise, for your case in particular, you can simply log out and back in, everything should be restored (since you want the extension removed).

**Comment by tony-nowatzki** [comment]
I tried logging out and back in (well, rebooting the computer), and actually resetting all gnome settings.  Nothing has seemed to work -- I hope I don't have to wipe the machine.

Can you tell me what log information would be useful?  I am happy to provide anything.

**Comment by franglais125** [comment]
The best bet would be to manually remove the extension by deleting the files from `.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me` (check whether it exists).

Perhaps something like:

```
cd ~/.local/share/gnome-shell/extensions/
rm -rf pixel-saver@deadalnix.me/
```

And then you can log out and back in.

**Comment by tony-nowatzki** [comment]
I tried that, no luck.  Is there somewhere else which might be retaining the information?

```
ls -alh ~/.local/share/gnome-shell/
total 16K
drwx------  2 tjn tjn 4.0K Aug 15 16:40 .
drwx------ 30 tjn tjn 4.0K Aug 15 14:47 ..
-rw-rw-r--  1 tjn tjn 2.6K Aug 15 16:40 application_state
-rw-rw-r--  1 tjn tjn  455 Aug 15 10:35 notifications
```

**Comment by franglais125** [comment]
What distro do you use? Have you installed the extension from the repos maybe?

**Comment by tony-nowatzki** [comment]
Ubuntu 18.04.  I originally installed it from the github by manually copying files and activating it by command line.  After removing the files manually didn't undo the changes, I also tried installing and uninstalling from the gnome extensions web app.

I also just now tried installing from the repos as suggested above, and uninstalling it (and logging out/in afterwards), which also didn't work.  

Do you think it would be feasible for me to modify the gnome settings manually to restore the original behavior?  (or somehow obtain the original configuration without re-installing the OS?)

**Comment by tony-nowatzki** [comment]
Actually, I just realized I should clarify something ... I no longer have ***any*** title bars after after having installed this app for the first time.  (not just limited to maximized windows)

**Comment by tony-nowatzki** [comment]
I just deleted ~/.config/gtk-3.0/ and this seemed to fix it.
