### ISSUE TITLE
gnome-shell 3.30: TypeError: global.screen is undefined

### ISSUE THREAD

**Issue by tkhai** [deadalnix/pixel-saver#176]
Pixel-saver stopped to work on gnome-shell 3:30 with error:
pro gnome-shell[23344]: Extension "pixel-saver@deadalnix.me" had error: TypeError: global.screen is undefined.

There is similar issue in dash-to-dock with fix available: https://github.com/micheleg/dash-to-dock/pull/770/commits/5fd2d0a73a88534871b149ba3322cb25f6c75aa3

**Comment by kirbyfan64** [comment]
I believe this has already been fixed, but a new version hasn't been released yet?

**Comment by d4rkf4b** [comment]
download
https://github.com/deadalnix/pixel-saver/raw/d97c6e4bd6dcb6ac5afd5250f05ecf7541096c69/pixel-saver%40deadalnix.me/decoration.js
https://github.com/deadalnix/pixel-saver/raw/d97c6e4bd6dcb6ac5afd5250f05ecf7541096c69/pixel-saver%40deadalnix.me/util.js
Replace them in ~/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/
Reload gnome-shell (alt+F2, r)
Seems to not be updated on [extensions.gnome.org](extensions.gnome.org)

**Comment by tkhai** [comment]
This helps. Thanks a lot, @d4rkf4b!

**Comment by highvoltage** [comment]
Would you also perhaps consider tagging a new release? Thanks :)
