### ISSUE TITLE
Pixel-saver does not remove the titlebar (3.30)

### ISSUE THREAD

**Issue by TheBlackKoala** [deadalnix/pixel-saver#179]
Pixel saver creates the window-corner in the activities-bar but does not remove the top bar (see screenshot).
![screenshot from 2018-10-04 11-47-08](https://user-images.githubusercontent.com/8694231/46466333-484b8f00-c7cb-11e8-97d1-43a3a0b2bd48.png)

**Comment by tallero** [comment]
Is `xprop` installed on your system? Are you using version from the extensions site or the one from here?

**Comment by tiotrom** [comment]
This is what I had to do to make it work with Gnome 3.30

> 
to make it work on Gnome 3.30 (and ubuntu 18.10 probably) : - edit$HOME/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/utils.js - edit$HOME/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/decorations.js replace global.screen by global.workspace_manager everywhere alt f2 r to restart gnome. Sorry for duplicate post, this one can be read :) Enjoy.

Taken from here https://extensions.gnome.org/extension/723/pixel-saver/

**Comment by tallero** [comment]
Support for 3.30 was merged way before GNOME 3.30 was out, see #178

**Comment by tiotrom** [comment]
I can only say that it didn't work for me until i did those changes manually. I had installed it from the above Gnome website.

**Comment by tallero** [comment]
@deadalnix is the owner of the extension on extensions.gnome.org, so he have to update the files there.

**Comment by tiotrom** [comment]
I see. Thanks!

**Comment by PohaoGit** [comment]
I just upgraded to Ubuntu 18.10(Gnome 3.30) and Pixel saver doesn't work.(loading error on the extension page)

**Comment by tallero** [comment]
@PohaoGit use these [instructions](https://github.com/deadalnix/pixel-saver#installation) to upgrade.

**Comment by PohaoGit** [comment]
> This is what I had to do to make it work with Gnome 3.30
> 
> > to make it work on Gnome 3.30 (and ubuntu 18.10 probably) : - edit$HOME/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/utils.js - edit$HOME/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/decorations.js replace global.screen by global.workspace_manager everywhere alt f2 r to restart gnome. Sorry for duplicate post, this one can be read :) Enjoy.
> 
> Taken from here https://extensions.gnome.org/extension/723/pixel-saver/

This works for me. Thanks

**Comment by TheBlackKoala** [comment]
Sorry i've had a busy time. I installed something (probably the version from here) and it works :)
