### ISSUE TITLE
Launching some windows uses 100% CPU.

### ISSUE THREAD

**Issue by kboone** [deadalnix/pixel-saver#25]
I ran into an issue with launching spotify with pixel-saver enabled. Calling `win.get_compositor_private()` in line 207 of `decoration.js` for this window always returns nil. This gets pixel-saver stuck in an infinite loop of calling `onWindowAdded`, using 100% CPU.

There should probably be some sort of max retries there. Simply disabling the callback to `onWindowAdded()` with `return false;` after the `if (!win.get_compositor_private()) {` call is a workaround, but probably not the right solution.

Thanks!

**Comment by deadalnix** [comment]
Is that valid that some window have no compositor at all ? (Against all expectation, I'm far from being a linux UI guru).

**Comment by kboone** [comment]
I don't know anything about this, sorry. I just traced down where it was getting stuck.

**Comment by kboone** [comment]
I took a deeper look. It looks like spotify is actually spawning 2 windows. One of these is processed fine, but the other is never actually displayed. I'm guessing that it is the login window, and it is probably created and then immediately closed because I'm already logged in. It could be that it is assigned a compositor, but that compositor is closed before the pixel-saver function gets to it. Regardless, it never has one when pixel-saver tries to call get_compositor_private()

**Comment by deadalnix** [comment]
OK I guess a retry limit of 3 or so should do the trick. Could you test this on your side and make a PR if it fixes things ?

I'm away from home right now and can't really work on a PR.

**Comment by kboone** [comment]
I'll give this a shot later today.

**Comment by kboone** [comment]
I created a pull request which fixes it for me. Thanks for maintaining this great extension!

**Comment by herrlado** [comment]
OK guys, I have also the same problem. I have pulled the version of @kboone and it solves the issue. Thanks!

**Comment by deadalnix** [comment]
Ok guys, sorry for the delays, I'm completely swamped. I'm just back home from that week end and have various things to catch up. Please ping that task if I forgot.

**Comment by herrlado** [comment]
Hey, everything is fine, it work, this is what matters :)

**Comment by deadalnix** [comment]
Is the new master work for you guys ? If yes, let's close this task.

**Comment by kboone** [comment]
Looks good!

**Comment by herrlado** [comment]
+1

**Comment by herrlado** [comment]
By the way, is there any way to debug a gnome shell extension?

**Comment by deadalnix** [comment]
You have some log function in pixel saver. They'll dump log in a system dependant location (because fuck convenience) so you'll have ask your distro guys to know where they go.

That is very inconvenient, but it works.

**Comment by kboone** [comment]
I used this:

```
journalctl /usr/bin/gnome-session -f -o cat
```

**Comment by chazzbg** [comment]
Hello there , i have noticed some issues with high load even with this fix. I'm using phpstorm and when i launch two windows of the ide ( for two different projects ), gnome-shell start to take up to 50% of the cpu. 
How could i debug this and provide some valuable information ?

**Comment by deadalnix** [comment]
The best thing you can do for a start is make sure this is due to the extension, by trying to disable all extension and repro. if it does repro, then it is a gnome shell problem.

Second step, enable just this extension and repro. If you can repro, then shit, that's on us :)

If not, try to enable other extension one by one and repro. This can come from this other extention, or a bad interaction betwen 2 extension.

If that is pixel saver, then edit the code to uncomment log line on top of various .js file. Then you need to find out where gnome shell dump its log (distro dependent, can't really tell you on that one) and provide what is logged by pixel saver while you repro.

**Comment by tupucula** [comment]
I got the same problem. Debian 8, gnome 3.14, pixel saver from extensions.gnome.org

Got this CPU load 5-30 minutes after session start. CPU goes up to 70%-90% and stays there until log out. No other extensions running, pretty sure the problem comes from pixel saver. Any more information needed?

**Comment by deadalnix** [comment]
There is a fix, but only for 3.16 . Debian package gnome 3.16 so you can upgrade.

**Comment by CrystalGamma** [comment]
I encounter these symptoms reliably when opening VLC player.
I'm running on master under GNOME 3.16, I guess the fix you are talking about is not yet there ...
If I can debug anything for you, tell me what.

**Comment by deadalnix** [comment]
The fix is in master. I'm not sure if it is on the gnome extension website yet.

**Comment by michaudg** [comment]
Same problem for me. 1 core at 22-25% when i launch Spotify. I had to reload the shell (alt-r, f2) to fix the problem. I'm on 3.16. If i disable pixel-saver and launch Spotify, CPU stay at 0%. Thanks.

**Comment by deadalnix** [comment]
This is supposed to be fixed in master, have you tried it ?

**Comment by michaudg** [comment]
Yes, i just cloned the project. Just tell me how i could help, I would do my best.

**Comment by deadalnix** [comment]
Well, there is something that is looping. First you need to find out where your distro is dumping gnome shell's logs. On my system, it is in the syslog, but it is going to depend on your distro.

Then, if you look at the source code, you'll find various LOG method with a commented line in them. Uncomment that line. This will make pixel saver dump a bunch of things in gnome shell's log.

Once you get that working, repro the bug. 100% CPU is a sign of something going into infinite loop. You should see some log entry repeat itself ad infinitum. If so, report it and that will tell what is using the CPU. If not, add more log into the shell and find it.

Once we know what is consuming your CPU, we can figure out how to fix it :)

**Comment by michaudg** [comment]
I uncommented all log() function in all .js files. Used "sudo journalctl -b /usr/bin/gnome-session" to see the logs. I launched Spotify and it seems that there is no errors :(

aoû 06 08:50:54 arch gnome-session[458]: Gjs-Message: JS LOG: [pixel-saver]: Override title Spotify
aoû 06 08:50:54 arch gnome-session[458]: Gjs-Message: JS LOG: [pixel-saver]: onWindowAdded: Spotify Premium - Linux Preview
aoû 06 08:50:54 arch gnome-session[458]: Gjs-Message: JS LOG: [pixel-saver]: setHideTitlebar: Spotify Premium - Linux Preview: true
aoû 06 08:50:54 arch gnome-session[458]: Gjs-Message: JS LOG: [pixel-saver]: xprop -id 0x220001e
aoû 06 08:50:54 arch gnome-session[458]: Gjs-Message: JS LOG: [pixel-saver]: Can't find original state for Spotify Premium - Linux Preview with id 0x220001e
aoû 06 08:50:54 arch gnome-session[458]: Gjs-Message: JS LOG: [pixel-saver]: xprop -id 0x220001e -f _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED 32c -set _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED 0x1

**Comment by deadalnix** [comment]
Ok, so first thing first: when you get to the 100% CPU situation, try to use htop or similar tool to check that gnome-shell process is the one using all that CPU.

As you don't seem to have a log of the error in your repro, you need to add more logs. What you can do is look for various call to Mainloop.idle_add and add a log before each of them. One of them is most likely where you get the 100% CPU.

**Comment by michaudg** [comment]
The bug is in this loop :  https://github.com/deadalnix/pixel-saver/blob/master/pixel-saver%40deadalnix.me/decoration.js#L214

I added log("spotify bug"); at line 215 and when i start Spotify, the log is filled with "spotify bug" message.

**Comment by hamiller** [comment]
can confirm line 215 does unfinite loop

**Comment by michaudg** [comment]
When Spotify starts, i can see in process manager that there is 3 processes named Spotify and 6 named SpotifyHelper. I will try to find a way to debug it in the extension.

**Comment by deadalnix** [comment]
Could you print the value of retry ? There should be at most 3 retry on that one, so I'd like to understand why it is indefinitely looping instead.

**Comment by michaudg** [comment]
the value of retry is 0

**Comment by deadalnix** [comment]
But, retry should be incremented here :(

https://github.com/deadalnix/pixel-saver/blob/master/pixel-saver%40deadalnix.me/decoration.js#L215

**Comment by michaudg** [comment]
i put log(retry); before onWindowAdded(), i will try to put it after...

**Comment by dffischer** [comment]
Look at this https://github.com/deadalnix/pixel-saver/blob/master/pixel-saver%40deadalnix.me/decoration.js#L209. It sets `retry` to 0 when it is _not_ undefined.

**Comment by michaudg** [comment]
before or after onWindowAdded(), retry is still at 0

**Comment by deadalnix** [comment]
:panda_face: 

Okayyyy...

**Comment by deadalnix** [comment]
Reversed the test, this should fix the issue. Could guys test with the new master ?

**Comment by michaudg** [comment]
it works! yay!

**Comment by hamiller** [comment]
@dffischer awesome! I've looked at it multiple times but haven't seen that :+1:

**Comment by dffischer** [comment]
And I never even experienced the bug myself. I just watch this great extension and thus was notified about your debugging. But I am glad I could help out. Keep up the good work.

**Comment by deadalnix** [comment]
Cool, this time it looks like it is fixed for good. Closing.
