### ISSUE TITLE
appMenu._label.setText is not a function

### ISSUE THREAD

**Issue by ariscop** [deadalnix/pixel-saver#28]
gnome-session[1829]: (gnome-shell:7240): Gjs-WARNING **: JS ERROR: TypeError: appMenu._label.setText is not a function
gnome-session[1829]: updateAppMenu@/home/andrew/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/app_menu.js:40

This breaks window titles
Wrapping it in a try/catch to silence the error and fixes titles, don't know enough about gnome-shell to debug myself

**Comment by deadalnix** [comment]
If yous tarted by telling what version of gnome and pixel saver you use, that would help.

**Comment by ariscop** [comment]
Gnome 3.16.2, Fedora 22
pixel-saver version 7

Problematic line is unchanged in current git

**Comment by deadalnix** [comment]
OK. The good news is that 3.16 has appeared in the experimental debian repo, so I'll be able to look into this. There is probably something that changed into the shell code, hard to say. The wonder of javascript.

**Comment by nueces** [comment]
Any news on this? I'm running shell version 3.16.3 with the pixel-saver version 7.0, on Debian Sid

**Comment by nueces** [comment]
This is fixed in the current master, the pull request #29 fix it in the commit https://github.com/deadalnix/pixel-saver/commit/d430657ec4a06b5ec6fda682cabb67646f0a0963

**Comment by marcohu** [comment]
This ticket can be closed?

**Comment by deadalnix** [comment]
Let's close it.
