### ISSUE TITLE
Can I set which icons Pixel Saver will use?

### ISSUE THREAD

**Issue by Pshemas** [deadalnix/pixel-saver#38]
Pixel Saver is such a saver ;) . But I encountered one issue - when I use Zukitwo theme and window decoration close/minize icons are being replaced by white dots (which ain't pretty). Is there a way to set "fixed" set of icons?

**Comment by deadalnix** [comment]
There is a a theme folder. Providing icon that matches your theme is probably the best way for you to get something good looking.

Also, your report makes me think that maybe there is a issue with unsupported themes. Do you have a screenshot or something ?

**Comment by Pshemas** [comment]
![pixelsaver_iconsissue](https://cloud.githubusercontent.com/assets/6144330/9845457/50129294-5acb-11e5-9e25-8d0f7c689bae.jpg)

I disagree that using tiltlebar icon is a good idea. Usually system bar and titlebar have very different looks - so icon that looks fine on titlebar can look completely out of place on system bar.
Ideally there would be a setting that would allow us to use a titlebar icon or use a custom one. But I understand that it may be a tedious task. So if there's a line of code I could modify to set up an icon chosen by me I'd be more than happy to do it - while I'm not a programmer that's the sort of tweaking I can handle for sure :) .

**Comment by deadalnix** [comment]
It does not need to be the same icon, but it needs to somehow fit with the theme. Please do not assume what is not in my message. There is theme folder, so you can provide icons that match your theme.

**Comment by Pshemas** [comment]
that was not my intention - well, the caveats of internet , not direct, communication.
Anyways thx for the pointers and making this awesome extension - problem fixed :) .
