### ISSUE TITLE
Woun't work for me

### ISSUE THREAD

**Issue by seriyps** [deadalnix/pixel-saver#4]
Non-maximized:
![pixel-saver](https://f.cloud.github.com/assets/422014/2118433/63a5d5da-9107-11e3-9575-28e6c18f2a16.png)

Maximized:
![2014-02-09 01 06 02](https://f.cloud.github.com/assets/422014/2118434/aba10ed6-9107-11e3-92e7-3b0f1f8ef63b.png)

So, title-bar doesn't dissapears, while additional buttons in activity bar are showed.

Ubuntu 13.10
Shell version: 3.8.4
Extension version: 2 (from metadata.json), installed from https://extensions.gnome.org

I tried with gdm and Lightdm with no success.
Maybe that's somehow related with my 2-monitor configuration.

Also, I've found following comment in decoration.js:
```
 * **Caveat**: doesn't work with Ubuntu's Ambiance and Radiance window themes -
 * my guess is they don't respect or implement this property.
```

**Comment by deadalnix** [comment]
Closing, as I have no idea if it is even fixable.
