### ISSUE TITLE
The window title is not displayed in Gnome 3.16's top bar

### ISSUE THREAD

**Issue by matachi** [deadalnix/pixel-saver#40]
A screenshot on Fedora 21 with Gnome 3.14.2:

![Gnome 3.14.2](http://i.imgur.com/wHwFoo3.png)

A screenshot on Fedora 22 with Gnome 3.16.2:

![Gnome 3.16.2](http://i.imgur.com/D00SI7Y.png)

As you can see, only the program's name is shown in the top bar in Gnome 3.16.2, while the window's title is shown in Gnome 3.14.2.

The version of Pixel Saver I'm using is the one found on https://extensions.gnome.org/extension/723/pixel-saver/.

**Comment by deadalnix** [comment]
Have you tried using the version from master ? Maybe the version in extension.gnome.org is a bit outdated, I'll have to upload a new one.

**Comment by matachi** [comment]
Brilliant, that fixed it. Is it possible to see how old the version on extension.gnome.org is?

**Comment by deadalnix** [comment]
Ok I'm not sure. I got to submit a new version to extension.gnome.org then.

**Comment by deadalnix** [comment]
I updated the version on extension.gnome.org . Closing.
