### ISSUE TITLE
Error: No signal 'maximize' on object 'ShellWM'

### ISSUE THREAD

**Issue by m45t3r** [deadalnix/pixel-saver#41]
Using pixel-saver in Gnome 3.18, while it seems to works gnome-tweak-tool shows that the extension didn't load correctly. Using LookingGlass to investigate this issue returns the error in the title.

**Comment by deadalnix** [comment]
Doesn't https://github.com/deadalnix/pixel-saver/pull/39 fixes it ?

it has been merged, so you can test using the latest pixel saver from that repository. if I can get some user to confirm it works well with 3.8, I'll update extension.gnome.org .

**Comment by m45t3r** [comment]
I am pretty sure I am using the lastest version from Git. I even tried to uninstall the plugin first, them reinstalled it.

Maybe there is some local cache copy. Where is the extensions stored in the home directory?

**Comment by deadalnix** [comment]
I don't think so. You may have several copies. You can uncomment some logs (there are log function on top of every files) and see if the shell spit them out.

**Comment by deadalnix** [comment]
Ok I was able to repro and I fixed it. Thank for the report. I submitted the updated extension to gnome, pending validation now.
