### ISSUE TITLE
3.20 compatibility

### ISSUE THREAD

**Issue by bytbox** [deadalnix/pixel-saver#57]
(At least for me) the only change necessary to get this to work with 3.20 is to add it to the version list in metadata.json.

**Comment by deadalnix** [comment]
Can you make a PR ?

**Comment by bytbox** [comment]
Done.

**Comment by deadalnix** [comment]
Merged

**Comment by killarny** [comment]
Just curious, is this fix uploaded to extensions.gnome.org? It doesn't appear to be active yet, but maybe we just have to wait longer for them to approve it?

**Comment by deadalnix** [comment]
Not at this point. I can do it soon, but I've been fairly swamped these days :/ I'm late in reviews as well.
