### ISSUE TITLE
Only one (close) button of three present in the top-bar

### ISSUE THREAD

**Issue by TheAngularMomentum** [deadalnix/pixel-saver#62]
When fullscreen, the three buttons do not show, only the close button shows up and all the other buttons are missing. Running Gnome 3.16.4 on Ubuntu

![vdlqzbh](https://cloud.githubusercontent.com/assets/11028919/14774157/8b83f7c2-0ad0-11e6-9197-e795829f10da.png)

**Comment by deadalnix** [comment]
pixel saver follow gnome's configuration. You should check it, for instance, using gnome-tweak-tool . My best guess here is that your theme or windows manager doesn't follow gnome's configuration.

**Comment by TheAngularMomentum** [comment]
I'm running Ubuntu Gnome with the Arc GTK and shell theme. I thought this was all compatible with this extension?

**Comment by deadalnix** [comment]
If you aren't willing to check what i tell you to, there is nothing I can do to help you.
