### ISSUE TITLE
Its not working on my gnome shell 3.20

### ISSUE THREAD

**Issue by gleydson404** [deadalnix/pixel-saver#65]
I made the installation process described here, and ist not working on my gnome 3.20.

**Comment by deadalnix** [comment]
I'm afraid it is not working is not precise enough to really help you.

**Comment by gleydson404** [comment]
@deadalnix how i colud be more precise ? there is some file that a could post to help you?

**Comment by gleydson404** [comment]
I'm doing exacly how you describe in read-me file, clone the project, going to the generated folder, and executing the comand to copy and to active the extension. In the terminal, is saying the extension is enabled, but in gnome tweak, the extension appears something like "Extension not compatible with this gnome version"

**Comment by deadalnix** [comment]
When did you try this ? 3.20 was merged only a few days ago.

**Comment by gleydson404** [comment]
I try today.

**Comment by gleydson404** [comment]
And  by the way. i'm really sorry about my english...

**Comment by deadalnix** [comment]
Ok please press alt+f2 . This should open a window with a text field. Type lg and press enter. This will open a debug window and there should be an "extension button". Can you tell me if there is something about pixel saver in there ?

Also, please try disabling other extension if you have some. Sometime there is conflict between extensions. If it works when all other extension are disabled, try to figure out which one conflicts.

**Comment by gleydson404** [comment]
I'm on arch, and im not able to do this, because when i presse alt+f2 its not happening nothing... How could i do this in terminal ? I mean, how can i do this what you are asking for in terminal ?

**Comment by deadalnix** [comment]
Ok please press alt+f2 . This should open a window with a text field. Type lg and press enter. This will open a debug window and there should be an "extension button". Can you tell me if there is something about pixel saver in there ?

Also, please try disabling other extension if you have some. Sometime there is conflict between extensions. If it works when all other extension are disabled, try to figure out which one conflicts.

**Comment by deadalnix** [comment]
I don't know much about arch. The thing you want to launch is https://wiki.gnome.org/Projects/GnomeShell/LookingGlass

**Comment by gleydson404** [comment]
[http://imgur.com/vigFDln](url) This is what happening, after i made the instalation process. For now, i cant run looking glass, and i'm looking for a way to do this. I'm sorry, i'm new on arch.

**Comment by marcohu** [comment]
I don't know whether it's possible to invoke LG from the terminal.

Pressing Alt+F2 should open the GNOME Shell command prompt (a little window with a textfield) where you have to enter 'lg' and press Enter. That should be all. I don't think this has changed with 3.20. 

If you still have problems you might want to ask in a Arch forum whether there are any peculiarities with their Gnome version. 

But any error messages can also be found in the log. You could use `journalctl` from the terminal.

**Comment by gleydson404** [comment]
@marcohu I try exacly what you are saying and its not happenings nothing. I already post in arch forum, and i'm waiting for answers.

**Comment by gleydson404** [comment]
I solve the problem to open gnome glass. @deadalnix i checked about pixel saver in the tab extensions in gnome glass, pixel saver is the first on the list.

**Comment by gleydson404** [comment]
http://i.imgur.com/siUaxSO.png is like this.

**Comment by 3nyder** [comment]
I had the same problem that you.
I used the master branch instead of the 1.7 tag
Maybe you could try doing that

**Comment by gleydson404** [comment]
@3nyder  How i do this?

**Comment by 3nyder** [comment]
`cd` into the folder of the project and type `git checkout master`, then copy and activate, just like in the README

Just to be sure, all steps needed
```
git clone https://github.com/deadalnix/pixel-saver.git
cd pixel-saver
# copy to extensions directory
cp -r pixel-saver@deadalnix.me -t ~/.local/share/gnome-shell/extensions
# activate
gnome-shell-extension-tool -e pixel-saver@deadalnix.me
```
by doing git clone, you should be on the master branch, so, there's no need to change the branch

**Comment by gleydson404** [comment]
I did and its not working @3nyder  :( when i type 'gnome-shell-extension-tool -e pixel-saver@deadalnix.me' is saying 'pixel-saver@deadalnix.me' is already enabled.

**Comment by 3nyder** [comment]
That's weird, i originally installed 1.7, then changed to master and copied the contents, and when i enabled the extension the message that i got was `'pixel-saver@deadalnix.me' is now enabled.`

Maybe you should try to disable it first with `gnome-shell-extension-tool -d pixel-saver@deadalnix.me` then you should delete the `pixel-saver` folder and try again, and reload gnome with alt-F2, write r and then pressing Enter, i read that you got problems with the command window, if nothing is appearing with alt-F2, you can also reload your gnome by login out and login in again.

Also, make sure that you are on the master branch when you copy the contents from the `pixel-saver` folder

**Comment by gleydson404** [comment]
now its enabled but its not hiding the top panel... @3nyder @deadalnix

**Comment by marcohu** [comment]
Use `sudo journalctl -f --id=gnome-session` to display the relevant log messages (tested on 3.18). 

Restart GNOME-Shell to reveal any messages that occur after startup.

**Comment by gleydson404** [comment]
http://pastebin.com/kuGFBXSx this is the output @marcohu.

**Comment by marcohu** [comment]
Have you restarted GNOME Shell after you've started showing the journal?

Alternatively, use the log viewer and filter for "gnome-session".

**Comment by gleydson404** [comment]
Yes, @marcohu  i had restarted. This could help ? http://imgur.com/aiJJvQI

**Comment by gleydson404** [comment]
http://imgur.com/oDPdkoa @3nyder @marcohu @deadalnix  this is normal ?

**Comment by deadalnix** [comment]
You should not be using extension.gnome.org with 3.20 . The version there doesn't support 3.20 . You need to run looking glass and/or look into the logs as @marcohu specified to know what the error is. Without knowing what the error is, there is no way to help you.

**Comment by gleydson404** [comment]
After i download the master version and change the permissions, the extension has changed the title of the windows, but its not hidding the top panel. I'm running looking glass and it's saying that there is no errors, and when i execute the command given by @marcohu, it's not showing nothing about pixel saver. I realy sorry my ignorance about dont knowing how to give feedback, i just want to fix this. :(

**Comment by gleydson404** [comment]
if you guys could see  [here](http://imgur.com/ZJW1kzW) in the picture, its changing the title, but its not hidding the bar. How could i see the logs? I mean, looking in the code, there is somethig like `LOG('setHideTitlebar: ' + win.get_title() + ': ' + hide);` where can i check this log ?

**Comment by gleydson404** [comment]
I solve the problem... Thankyou guys, The problem, was, that a was missing  a package, xorg-utils,  I installed and it works now.
