### ISSUE TITLE
Doesn't work properly on Gnome 3.12

### ISSUE THREAD

**Issue by geecko86** [deadalnix/pixel-saver#7]
By default, some apps start maximized. E.g. firefox. This is what happens : http://puu.sh/83f79.png

The decoration bar is displayed (but it shouldn't), but so are the pixel-saver buttons. If I reduce the window and the maximize it back, it works fine. Sometimes changing the focus to another window fixes it too.

Also, when the decoration bar is displayed, the buttons don't work.

**Comment by deadalnix** [comment]
I think we can close that one.
