### ISSUE TITLE
Update release on extensions.gnome.org

### ISSUE THREAD

**Issue by BoBeR182** [deadalnix/pixel-saver#79]
https://extensions.gnome.org/extension/723/pixel-saver/ is still not compatible with version 3.20

**Comment by select** [comment]
I wonder if there is a version that I can manually install right now since I'm facing the same problem.

**Comment by select** [comment]
Ok I followed the install instructions from the README and forgot to restart the shell `gnome-shell -r` now it works! Nice.

**Comment by deadalnix** [comment]
it has been update a while back. Closing.

Usually when i have a new version supported, I send a version to extension.gnome.org , but the review process can take some time there.
