### ISSUE TITLE
incompatibility with the new gnome-shell 3.20.3

### ISSUE THREAD

**Issue by victorfeijo** [deadalnix/pixel-saver#84]
I already changed the metadata.json to 3.20.3 and still don't working.

**Comment by victorfeijo** [comment]
Changed the metadata.json to just 3.20 and restarted the gnome-shell worked for me, thanks!

**Comment by deadalnix** [comment]
I'm afraid not working is not an actionable feedback. I'm happy that you made it work. However, if you want support in the future, try to at least describe what is not working.
