### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by omeryagmurlu** [deadalnix/pixel-saver#87]
I've read the README, but it doesn't matter, configuration is MANDATORY for any application, plugin, whatever, even more when that application is implementing multiple independent features (In this case, topbar icons and title bar).

Look at these apps for good configs:

https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/
https://extensions.gnome.org/extension/708/panel-osd/
https://extensions.gnome.org/extension/977/recent-items/

I'd love to send a merge request, but don't have time leider.

This is a convienent extension you made, improve it by allowing configurations.

**Comment by deadalnix** [comment]
There is nothing actionable in this issue. Without mention of what configuration you are missing, there is not much to discuss. Writing MANDATORY in capital doesn't change anything.

Configuration come with a high price. Higher code complexity to handle various configuration, maintenance of the configuration screen, migration of configuration data from a version to the next, translations (yes, there are a TON of people outside the UK/US). Apparently, you have no time to manage this.
