### ISSUE TITLE
Unable to enable extension

### ISSUE THREAD

**Issue by wieczorek1990** [deadalnix/pixel-saver#89]
Extension is greyed out in `gnome-shell-extension-prefs` 

```
$ gnome-shell --version
GNOME Shell 3.21.91
```

**Comment by deadalnix** [comment]
Indeed, that version issnot supported yet. Can you update the manifest file
and see if that works ? If not, what problems do you face ?

**Comment by zapashcanon** [comment]
It works fine with 3.21.

**Comment by deadalnix** [comment]
Alright, let's update the manifest, then.

**Comment by wieczorek1990** [comment]
```
luke ~/S/pixel-saver $ cat pixel-saver@deadalnix.me/metadata.json 
{
	"uuid": "pixel-saver@deadalnix.me",
	"name": "Pixel Saver",
	"description": "Pixel Saver is designed to save pixel by fusing activity bar and title bar in a natural way",
	"url": "https://github.com/deadalnix/pixel-saver",
	"shell-version": ["3.16", "3.18", "3.20", "3.21"]
}
```

Still grayed out.

**Comment by deadalnix** [comment]
It does looks like 3.22 is due by the end of the month. I thin the best it to bump to 3.22 once it is released. 3.21 is unstable and therefore, I'm not sure how much effort should be put in it.

**Comment by zapashcanon** [comment]
3.21 is just the dev name of 3.22 ; so it'll also work on 3.22.

Just add 3.22 to `metadata.json` as 3.21 is just a temporary release.

**Comment by qyin** [comment]
The gnome version of current Debian Testing is 3.21.59.
```
$ gnome-shell --version
GNOME Shell 3.21.91
```
The method mentioned by @wieczorek1990  is not working. I also test the latest commit 3738e86, same situation. Any  suggestion?

**Comment by zapashcanon** [comment]
@qyin , you've got to add `3.21.91` and not just `3.21`.

**Comment by qyin** [comment]
@zapashcanon It works! Thank you very much.

**Comment by deadalnix** [comment]
Alright, it is updated on extension.gnome.org as well, closing,
