### ISSUE TITLE
Issues with the way icons are displayed

### ISSUE THREAD

**Issue by nunocastromartins** [deadalnix/pixel-saver#90]
Hi! Somehow, this extension is not displaying its icons in the same way other extensions do, i.e. there is probably some standard way of displaying icons on the top bar, and this extension is not following it.

This is a screenshot using the default Adwaita theme:
![screenshot from 2016-09-19 01-02-51](https://cloud.githubusercontent.com/assets/8314616/18620173/e5892a1a-7e04-11e6-9ed4-ca14f10f6f63.png)

Here with the other buttons:
![screenshot from 2016-09-19 01-05-52](https://cloud.githubusercontent.com/assets/8314616/18620186/45156e94-7e05-11e6-9512-cae279db617a.png)

The spacing between the three first icons is the default, between the third icon and this extension's icons is not.

The spacing is not the only issue. Some themes define mouse-over styles on the icons, such styles do not apply to this extension's icons.

For example, using the Arc theme:
![screenshot from 2016-09-19 01-12-50](https://cloud.githubusercontent.com/assets/8314616/18620238/55d535ba-7e06-11e6-9f3b-bd9600bd3b9e.png)

The style on the third icon on the picture, caused by moving the mouse over the icon, does not trigger for this extension's icons.

I've never written a Gnome Shell Extension, so I really don't know for sure, but my take on this is that the icons should be placed inside some container, some `div` with some specific `class`, or something of the sort.

Thank you for you work so far!

**Comment by deadalnix** [comment]
I've noticed that as well, but have no idea how other extension do it. Do you have some code I can look at ?

**Comment by nunocastromartins** [comment]
I've actually reported a similar issue on another extension, the `todo.txt` one. It's not exactly the same, but it seems related.

The developer managed to fix it. Maybe you can check the code to see what he's doing, or maybe contact him?

The issue: https://bitbucket.org/bartl/todo.txt-bart.libert.gmail.com/issues/86/icon-shadow
The commit that fixed it: https://bitbucket.org/bartl/todo.txt-bart.libert.gmail.com/commits/f9cae1bcb49d

He seems to create a `St.Icon` instance with a `system-status-icon` CSS class.
Again, not exactly the same issue, but I thought it might be related.

**Comment by deadalnix** [comment]
Alright, it looks like things are much more fubared in that extension than it was in in the todo one :) That'ss require some rewrite, but at least now I have a model of how to do things properly.

**Comment by deadalnix** [comment]
Can you try the fixbuttons branch and see how that goes ? This is work in progress, so there may be other issues.

**Comment by nunocastromartins** [comment]
Hi, I gave it a try.
The mouse over style now appears when moving the cursor over the icons, which is nice!
The spacing between the icons is still different from the other extensions, though.

Also, not sure if intended, but the red close button from the Arc theme has been replaced by a small white cross.

**Comment by deadalnix** [comment]
Thanks for testing. No the white cross is not expected, but I was expecting bugs, I ended having to revamp the button code to get that working. It is unclear how to solve all the issue with theming.

**Comment by ZJaume** [comment]
I have Arc-Darker theme and this is the way that icons are displayed:
Unmaximized:
![captura de pantalla de 2017-01-24 16-57-15](https://cloud.githubusercontent.com/assets/11339330/22255017/5f4748f4-e256-11e6-8433-826cf49a86b4.png)
Maximized:
![captura de pantalla de 2017-01-24 16-57-24](https://cloud.githubusercontent.com/assets/11339330/22255021/6180116e-e256-11e6-8af7-86d211dfac42.png)
I think the icons maximized should appear in the dark way. I'm not sure if it is related with this issue.

**Comment by deadalnix** [comment]
Not sure. I have some update on this. The problem is, there are 2 ways that these icons could be displayed, and, depending on the theme, one looks good and the other ugly and vice versa. I haven't been able to have both looks good so far :(
