### ISSUE TITLE
Window icons are not displayed if window is 'drag maximized'

### ISSUE THREAD

**Issue by harpdev** [deadalnix/pixel-saver#92]
When a window is maximized by dragging to the top of the screen, pixel-saver hides window decoration as expected, but does not display the window icons on the panel.

![output1](https://cloud.githubusercontent.com/assets/16774664/19216416/ce63209e-8db2-11e6-9f0f-3917ebb0e46b.gif)

**Comment by harpdev** [comment]
Also tested with all other extensions disabled.

**Comment by zapashcanon** [comment]
Same here.

**Comment by deadalnix** [comment]
Thanks for the bug report, I'll try figure that out. Anything unusual in
your setup ?

2016-10-09 17:00 GMT-07:00 Léo Andrès <notifications@github.com>:

**Comment by zapashcanon** [comment]
I don't see anything unusual... I'm using a lot of extensions, I'll try without them but as @harpdev already confirmed it occurs in this case, I'm not sure it could be useful.

**Comment by harpdev** [comment]
Tested with a fresh install of Ubuntu Gnome and the same behavior occurs.

**Comment by miguejinn** [comment]
Same in Debian Testing with Gnome3 (3.20).
Also get the same behavior when I drag a window left or right and it maximized on half window.

**Comment by satriani-vai** [comment]
Take a look here https://github.com/deadalnix/pixel-saver/pull/82

**Comment by deadalnix** [comment]
@miguejinn You shouldn't get the bar to disappear when you maximize left or right.

I'm not sure what the hell is going on here as I do not repro on my end. Probably some timing issue in the event triggered, or some combination of version.

**Comment by miguejinn** [comment]
@deadalnix The bar dissapear, but the icons are not displayed, unless if I do it after maximize normally.

**Comment by deadalnix** [comment]
This is fixed now.
