### ISSUE TITLE
Not working with gnome-terminal 3.22

### ISSUE THREAD

**Issue by cxnam** [deadalnix/pixel-saver#93]
Hello,
I use gnome-terminal 3.22 on fedora 25 and not working with pixel-saver 1.9
![screenshot from 2016-10-18 09-39-19](https://cloud.githubusercontent.com/assets/5145416/19462493/41f7b400-9517-11e6-852d-73d969a21d6b.png)

**Comment by mrPjer** [comment]
I think this is related to #32

**Comment by cxnam** [comment]
@mrPjer oh, tks for reply

**Comment by deadalnix** [comment]
Ok closing as this is duplicated. I'm aware this isn't working with wayland as it should. I'm trying to figure out a fix, but at this stage, I'm not even sure there is a way :/

**Comment by cxnam** [comment]
@deadalnix tks, i switch to Xorg and work fine.
![screenshot from 2016-11-21 14-31-44](https://cloud.githubusercontent.com/assets/5145416/20474082/4f074ad4-aff7-11e6-9355-edc8bbc8ed60.png)

**Comment by deadalnix** [comment]
So I reached to the gnome team for the wayland problem and its not sure
there is a solution so far :/

**Comment by jhasse** [comment]
This is a duplicate of #32, let's discuss this there :)
