### ISSUE TITLE
Theme applies only after relogging

### ISSUE THREAD

**Issue by Tefached95** [deadalnix/pixel-saver#94]
Using Arch Linux + GNOME 3.22 on Wayland

On first boot, the default theme is used, but when I sign out and then back in, or if the screen locks itself and I log back in, the correct theme is applied (Arc in my case).

**Comment by christianbueno1** [comment]
hello pal, what extension are you using for the size of the title window of your terminal window.
[ unmaximized window](http://i.imgur.com/swc4Gt3.png)

**Comment by deadalnix** [comment]
@Tefached95 At every boot ?
@christianbueno1 It's not an extension, I programmed my own terminal using gtk's VTE: https://github.com/deadalnix/derminal

**Comment by Tefached95** [comment]
@deadalnix Aye, at absolutely every boot, without fail. I've actually gotten into a habit of turning on my laptop, and immediately locking my screen to get the theme to apply lol.

**Comment by deadalnix** [comment]
Hi,

Can you check the branch fixbuttons and tel me if it works ? There may be other issues, this is a work in progress, but I think this should solve the theme issue.

**Comment by deadalnix** [comment]
Can you guys try the branch themefix and tell me how it goes ?

**Comment by Tefached95** [comment]
@deadalnix Terribly sorry, I've since had to move from Arch over to Windows so I can't try the branch. If I get the opportunity on another machine I'll let you know how it goes.

**Comment by deadalnix** [comment]
This should be fixed in master.

**Comment by trgeiger** [comment]
This appears to still be an issue in Arch using Gnome in Wayland.
