### ISSUE TITLE
Compatibility issues with Window List extension.

### ISSUE THREAD

**Issue by tushar9989mn** [deadalnix/pixel-saver#99]
It causes the windows to minimize. My gnome version is 3.18 on Ubuntu 16.04 LTS.
![screenshot from 2016-11-30 14-02-46](https://cloud.githubusercontent.com/assets/20472016/20745133/e07cfc60-b705-11e6-86ca-2428846db34b.png)
![screenshot from 2016-11-30 14-03-38](https://cloud.githubusercontent.com/assets/20472016/20745135/e286518c-b705-11e6-8ad2-52c32125d057.png)

**Comment by antmak** [comment]
I confirm this bug

![screenshot from 2017-02-27 17-10-54](https://cloud.githubusercontent.com/assets/675314/23357341/fc1ccc2a-fd0f-11e6-9ebc-14b96bfde422.png)

Don't modify WindowsList-buttons please

**Comment by antmak** [comment]
#108 does not fix this bug, as I had hoped.
